"""Init

Revision ID: 3f295e558c06
Revises: 
Create Date: 2024-12-06 19:45:56.769409

"""



from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3f295e558c06"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "clients",
        sa.PrimaryKeyConstraint("id"),
        sa.Column("name", sa.String(length=30), nullable=False),
        sa.Column("sur_name", sa.String(length=30), nullable=False),
        sa.Column("middle_name", sa.String(length=30), nullable=True),
        sa.Column("create_at_day", sa.Date(), nullable=False),
        sa.Column("update_at_day", sa.Date(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        
    )
    op.create_table(
        "contacts",
        sa.PrimaryKeyConstraint("id"),
        sa.Column("client_id", sa.Integer(), nullable=False),
        sa.Column(
            "phone_number",
            sqlalchemy_utils.types.phone_number.PhoneNumberType(length=20),
            nullable=False,
        ),
        sa.Column(
            "email",
            sqlalchemy_utils.types.email.EmailType(length=255),
            nullable=False,
        ),
        sa.Column("facebook", sa.String(length=30), nullable=True),
        sa.Column("vk", sa.String(length=30), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
        ),
        
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("phone_number"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("contacts")
    op.drop_table("clients")
    # ### end Alembic commands ###
