"""new table in db

Revision ID: caf63c2107ae
Revises: 
Create Date: 2025-01-05 17:09:12.537992

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "caf63c2107ae"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "clients",
        sa.Column("name", sa.String(length=30), nullable=False),
        sa.Column("sur_name", sa.String(length=30), nullable=False),
        sa.Column("middle_name", sa.String(length=30), nullable=True),
        sa.Column(
            "create_at_day",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("update_at_day", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "contacts",
        sa.Column("client_id", sa.Integer(), nullable=False),
        sa.Column("phone_number", sa.String(length=10), nullable=False),
        sa.Column("email", sa.String(length=100), nullable=False),
        sa.Column("facebook", sa.String(length=30), nullable=True),
        sa.Column("vk", sa.String(length=30), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("phone_number"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("contacts")
    op.drop_table("clients")
    # ### end Alembic commands ###
